import Head from 'next/head'
import '../styles/globals.scss'

function MyApp({ Component, pageProps }) {
	console.log("====app");
	return (
		<>
			<Head>
				<title>nextjs test</title>
				<meta name="description" content="Generated by create next app" key="description" />
				<meta property="og:title" content="nextjs test" key="title" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Component {...pageProps} />
		</>
	)
}

export default MyApp